api_key: vbrm_openvidu_key
api_secret: vbrm_openvidu_secret_2024_secure_key
ws_url: ws://livekit:7880

redis:
  address: redis:6379
  password: VbrmRedis2024Secure

s3:
  access_key: IJE1GG708IQ2LEH7I2AS
  secret: PV7b+H48T5k0lSMnkjnu+tYdZTnBzwdiQCEo7mBj
  region: us-east-1
  endpoint: https://s3.iamucchash.com
  bucket: bankvision-mtb-ext
  force_path_style: true

health_port: 8080
prometheus_port: 9090
log_level: info

backup_storage: /home/egress/backup_storage
