port: 7880
bind_addresses:
  - 0.0.0.0
rtc:
  port_range_start: 50000
  port_range_end: 50050
  tcp_port: 7881
  use_external_ip: false
  enable_loopback_candidate: true

redis:
  address: redis:6379
  password: VbrmRedis2024Secure

keys:
  vbrm_openvidu_key: vbrm_openvidu_secret_2024_secure_key

webhook:
  api_key: vbrm_openvidu_key
  urls:
    - http://core-api.bankvision-app.svc.cluster.local:8443/api/webhook/livekit

turn:
  enabled: false
